### ISSUE TITLE
Assertion Failure - "Don't know about flushed view" crash

### ISSUE THREAD

**Issue by daviddelmonte** [conmulligan/TabBarPageController#1]
Hi. I like your control, so Thanks! 

I am getting this crash though from time to time. This [q/a on StackOverflow](https://stackoverflow.com/questions/42833765/assertion-failure-in-uipageviewcontroller) dives into the possible causes and solutions.

**Comment by conmulligan** [comment]
Thanks for the heads up, I’ll try to reproduce. Can you let me know how many tabs you had added when the crash occurred?

**Comment by conmulligan** [comment]
Fixed in 0.1.2.

**Comment by daviddelmonte** [comment]
Thanks Conor. Apologies for late response — I’ve been traveling extensively.

David
